// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $bill_index from "./routes/bill/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $society_homePage from "./routes/society/homePage.tsx";
import * as $society_index from "./routes/society/index.tsx";
import * as $buttons from "./islands/buttons.tsx";
import * as $sidebar_item from "./islands/sidebar-item.tsx";
import * as $sidebar from "./islands/sidebar.tsx";
import * as $bill_islands_cycle from "./routes/bill/(_islands)/cycle.tsx";
import * as $bill_islands_flowBitSidebar from "./routes/bill/(_islands)/flowBitSidebar.tsx";
import * as $bill_islands_generate_bill from "./routes/bill/(_islands)/generate-bill.tsx";
import * as $bill_islands_grid_component from "./routes/bill/(_islands)/grid-component.tsx";
import * as $society_islands_review from "./routes/society/(_islands)/review.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/bill/index.tsx": $bill_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/society/homePage.tsx": $society_homePage,
    "./routes/society/index.tsx": $society_index,
  },
  islands: {
    "./islands/buttons.tsx": $buttons,
    "./islands/sidebar-item.tsx": $sidebar_item,
    "./islands/sidebar.tsx": $sidebar,
    "./routes/bill/(_islands)/cycle.tsx": $bill_islands_cycle,
    "./routes/bill/(_islands)/flowBitSidebar.tsx": $bill_islands_flowBitSidebar,
    "./routes/bill/(_islands)/generate-bill.tsx": $bill_islands_generate_bill,
    "./routes/bill/(_islands)/grid-component.tsx": $bill_islands_grid_component,
    "./routes/society/(_islands)/review.tsx": $society_islands_review,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
