// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $society_homePage from "./routes/society/homePage.tsx";
import * as $buttons from "./islands/buttons.tsx";
import * as $sidebar_item from "./islands/sidebar-item.tsx";
import * as $sidebar from "./islands/sidebar.tsx";
import * as $society_islands_review from "./routes/society/(_islands)/review.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/society/homePage.tsx": $society_homePage,
  },
  islands: {
    "./islands/buttons.tsx": $buttons,
    "./islands/sidebar-item.tsx": $sidebar_item,
    "./islands/sidebar.tsx": $sidebar,
    "./routes/society/(_islands)/review.tsx": $society_islands_review,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
